mapreduce: FilePool Class Reference
FilePool Class Reference
Class FilePool - works with a file pool.
#include <FilePool.h>
Public Member Functions
FilePool (fs::path path, std::size_t files_count, std::ios_base::openmode mode)
virtual ~FilePool ()
void write (std::size_t index, const Data &data)
void write (std::size_t index, const std::vector< Data > &v_data)
Data read (std::size_t index)
std::vector< Data > read_all (std::size_t index)
void close (std::size_t index)
Protected Attributes
std::size_t _files_count
Private Attributes
std::vector< std::fstream > _file_pool
std::ios_base::openmode _mode
fs::path _path
Detailed Description
Class FilePool - works with a file pool.
Parameters
path Path to the files, (including the filename).
files_count Count of files.
mode Opening mode.
Definition at line 27 of file FilePool.h.
Constructor & Destructor Documentation
FilePool()
FilePool::FilePool (fs::path path, std::size_t files_count, std::ios_base::openmode mode)
Definition at line 3 of file FilePool.cpp.
    : _mode(mode), _path(std::move(path)), _files_count(files_count) {
    _file_pool.resize(_files_count);
    fs::path filename = _path.filename();
    fs::path dir = _path.remove_filename();
    for (std::size_t i = 0; i < _files_count; ++i) {
        _file_pool[i].open(dir/(filename.string() + std::to_string(i)), mode);
        if (!_file_pool[i].is_open()) {
            std::cerr << "File opening error: " << filename.string() + std::to_string(i) << std::endl;
        }
    }
}
~FilePool()
FilePool::~FilePool () virtual
Definition at line 16 of file FilePool.cpp.
                    {
    for (auto& file : _file_pool) {
        file.close();
    }
}
Member Function Documentation
close()
void FilePool::close (std::size_t index)
Definition at line 54 of file FilePool.cpp.
{
    _file_pool[index].close();
}
Referenced by MapReduce::run_shuffler().
read()
Data FilePool::read (std::size_t index)
Definition at line 35 of file FilePool.cpp.
{
    Data data;
    if (index < _file_pool.size() && (std::ios::in & _mode)) {
        _file_pool[index] >> data.key >> data.value;
    }
    return data;
}
Referenced by main(), MapReduce::run_combiners(), MapReduce::run_reducers(), and MapReduce::run_shuffler().
read_all()
std::vector< Data > FilePool::read_all (std::size_t index)
Definition at line 43 of file FilePool.cpp.
{
    std::vector<Data> v_data;
    if (index < _file_pool.size() && (std::ios::in & _mode)) {
        Data data;
        while (_file_pool[index] >> data.key >> data.value) {
            v_data.push_back(data);
        }
    }
    return v_data;
}
Referenced by TEST().
write() [1/2]
void FilePool::write (std::size_t index, const Data & data)
Definition at line 22 of file FilePool.cpp.
{
    if (index < _file_pool.size() && (std::ios::out & _mode)) {
        _file_pool[index] << data.key << " " << data.value << std::endl;
    }
}
Referenced by MapReduce::run_mappers(), MapReduce::run_reducers(), and ShufflerFilePool::sequential_write().
write() [2/2]
void FilePool::write (std::size_t index, const std::vector< Data > & v_data)
Definition at line 28 of file FilePool.cpp.
{
    if (index < _file_pool.size() && (std::ios::out & _mode)) {
        for (const auto& data : v_data)
        _file_pool[index] << data.key << " " << data.value << std::endl;
    }
}
Member Data Documentation
_file_pool
std::vector<std::fstream> FilePool::_file_pool private
Definition at line 40 of file FilePool.h.
Referenced by close(), FilePool(), read(), read_all(), write(), and ~FilePool().
_files_count
std::size_t FilePool::_files_count protected
Definition at line 45 of file FilePool.h.
Referenced by FilePool(), and ShufflerFilePool::sequential_write().
_mode
std::ios_base::openmode FilePool::_mode private
Definition at line 41 of file FilePool.h.
Referenced by read(), read_all(), and write().
_path
fs::path FilePool::_path private
Definition at line 42 of file FilePool.h.
Referenced by FilePool().
The documentation for this class was generated from the following files:
FilePool.h
FilePool.cpp