mapreduce: MapReduce Class Reference
MapReduce Class Reference
Class MapReduce - MapReduce framework.
#include <MapReduce.h>
Classes
struct Block
Public Member Functions
MapReduce (int mappers_count, int reducers_count, fs::path work={"./work/"})
void run (const fs::path &input, const fs::path &output)
void set_mapper (mapper_type mapper)
void set_combiner (combiner_type combiner)
void set_reducer (reducer_type reducer)
std::string get_output_filename ()
Private Member Functions
std::size_t run_mappers (const std::vector< Block > &blocks, const fs::path &input)
std::size_t run_combiners ()
void run_shuffler (std::size_t data_size) const
void run_reducers (const fs::path &output)
Static Private Member Functions
static std::vector< Block > split_file (const fs::path &path, std::size_t blocks_count)
Private Attributes
std::size_t _mappers_count
std::size_t _reducers_count
mapper_type _mapper
combiner_type _combiner
reducer_type _reducer
const std::string _mapper_out {"mapper_out"}
const std::string _combiner_out {"combiner_out"}
const std::string _reducer_in {"reducer_in"}
const std::string _reducer_out {"reducer_out"}
fs::path _work
Detailed Description
Class MapReduce - MapReduce framework.
Parameters
mappers_count Count of mappers.
reducers_count Count of reducers.
work Work directory.
Definition at line 20 of file MapReduce.h.
Constructor & Destructor Documentation
MapReduce()
MapReduce::MapReduce (int mappers_count, int reducers_count, fs::path work = {"./work/"})
Definition at line 3 of file MapReduce.cpp.
        : _mappers_count(mappers_count), _reducers_count(reducers_count), _work(std::move(work)) {
    if (!fs::exists(_work)) {
        fs::create_directory(_work);
    }
}
Member Function Documentation
get_output_filename()
std::string MapReduce::get_output_filename ()
Definition at line 34 of file MapReduce.cpp.
{
    return _reducer_out;
}
Referenced by main().
run()
void MapReduce::run (const fs::path & input, const fs::path & output)
Definition at line 10 of file MapReduce.cpp.
{
    auto blocks = split_file(input, _mappers_count);
    run_mappers(blocks, input);
    std::size_t data_size = run_combiners();
    run_shuffler(data_size);
    run_reducers(output);
}
Referenced by main(), and run_mapreduce().
run_combiners()
std::size_t MapReduce::run_combiners () private
Definition at line 97 of file MapReduce.cpp.
{
    FilePool mapper_out(_work/_mapper_out, _mappers_count, std::ios::in);
    FilePool combiner_out(_work/_combiner_out, _mappers_count, std::ios::out);
    std::vector<std::future<std::size_t>> combiners_futures(_mappers_count);
    for (std::size_t i = 0; i < _mappers_count; ++i) {
        combiners_futures[i] = std::async(std::launch::async, [&, i]() {
            std::size_t count = 0;
            Data result, temp;
            for (Data data = mapper_out.read(i); !data.key.empty();) {
                result = _combiner(data, temp);
                if (!result.key.empty()) {
                    combiner_out.write(i, result);
                    ++count;
                }
                data = mapper_out.read(i);
            }
            if (!temp.key.empty()) {
                combiner_out.write(i, temp);
                ++count;
            }
            return count;
        });
    }
    return std::accumulate(combiners_futures.begin(), combiners_futures.end(), 0,
                           [](std::size_t a, std::future<std::size_t>& b) {return a + b.get();});
}
Referenced by run().
run_mappers()
std::size_t MapReduce::run_mappers (const std::vector< Block > & blocks, const fs::path & input) private
Definition at line 61 of file MapReduce.cpp.
{
    FilePool mapper_out(_work/_mapper_out, _mappers_count, std::ios::out);
    std::vector<std::future<std::size_t>> mappers_futures(_mappers_count);
    for (std::size_t i_mapper = 0; i_mapper < _mappers_count; ++i_mapper) {
        mappers_futures[i_mapper] = std::async(std::launch::async, [&, i_mapper]() {
            std::ifstream input_file(input, std::ios::binary);
            std::vector<Data> result;
            char ch;
            std::string line;
            input_file.seekg(blocks[i_mapper].from);
            for (std::size_t i = blocks[i_mapper].from; i <= blocks[i_mapper].to; ++i) {
                input_file.read(&ch, sizeof(char));
                if (ch != '\n') {
                    if (ch != '\r') {
                        line += ch;
                    }
                } else {
                    result.push_back(_mapper(line));
                    line.clear();
                }
            }
            input_file.close();
            std::sort(result.begin(), result.end(),
                      [](const Data& a, const Data& b) {return a.key < b.key;});
            mapper_out.write(i_mapper, result);
            return std::size_t {result.size()};
        });
    }
    return std::accumulate(mappers_futures.begin(), mappers_futures.end(), 0,
                           [](std::size_t a, std::future<std::size_t>& b) {return a + b.get();});
}
Referenced by run().
run_reducers()
void MapReduce::run_reducers (const fs::path & output) private
Definition at line 152 of file MapReduce.cpp.
{
    FilePool reducer_in(_work/_reducer_in, _reducers_count, std::ios::in);
    FilePool reducer_out(output/_reducer_out, _reducers_count, std::ios::out);
    std::vector<std::future<void>> reducers_futures(_reducers_count);
    for (std::size_t i_reducer = 0; i_reducer < _reducers_count; ++i_reducer) {
        reducers_futures[i_reducer] = std::async(std::launch::async, [&, i_reducer]() {
            Data result;
            for (Data data = reducer_in.read(i_reducer); !data.key.empty();) {
                result = _reducer(result, data);
                data = reducer_in.read(i_reducer);
            }
            reducer_out.write(i_reducer, result);
        });
    }
    for (auto& future : reducers_futures) {
        future.wait();
    }
}
Referenced by run().
run_shuffler()
void MapReduce::run_shuffler (std::size_t data_size) const private
Definition at line 125 of file MapReduce.cpp.
{
    struct FileData {
        Data data;
        std::size_t file_index;
    };
    FilePool combiner_out(_work/_combiner_out, _mappers_count, std::ios::in);
    ShufflerFilePool reducer_in(_work/_reducer_in, _reducers_count, std::ios::out, data_size);
    std::vector<FileData> buffer;
    for (std::size_t i = 0; i < _mappers_count; ++i) {
        buffer.push_back(FileData{combiner_out.read(i), i});
    }
    while (!buffer.empty()) {
        auto min_it = std::min_element(buffer.begin(), buffer.end(),
            [](const FileData &a, const FileData &b) {return a.data.key < b.data.key;});
        reducer_in.sequential_write(min_it->data);
        min_it->data = combiner_out.read(min_it->file_index);
        if (min_it->data.key.empty()) {
            combiner_out.close(min_it->file_index);
            buffer.erase(min_it);
        }
    }
}
Referenced by run().
set_combiner()
void MapReduce::set_combiner (combiner_type combiner)
Definition at line 26 of file MapReduce.cpp.
{
    _combiner = std::move(combiner);
}
Referenced by main(), and run_mapreduce().
set_mapper()
void MapReduce::set_mapper (mapper_type mapper)
Definition at line 22 of file MapReduce.cpp.
{
    _mapper = std::move(mapper);
}
Referenced by main(), and run_mapreduce().
set_reducer()
void MapReduce::set_reducer (reducer_type reducer)
Definition at line 30 of file MapReduce.cpp.
{
    _reducer = std::move(reducer);
}
Referenced by main(), and run_mapreduce().
split_file()
std::vector< MapReduce::Block > MapReduce::split_file (const fs::path & path, std::size_t blocks_count) static private
Definition at line 38 of file MapReduce.cpp.
{
    std::uintmax_t file_size = fs::file_size(path);
    std::size_t block_size = file_size / blocks_count;
    std::vector<Block> blocks(blocks_count);
    std::size_t low_boundary = 0, high_boundary;
    std::ifstream input_file(path, std::ios::binary);
    for (std::size_t i = 1; i < blocks_count; ++i) {
        input_file.seekg(i * block_size);
        char ch;
        do {
            input_file.read(&ch, sizeof(char));
        } while (ch != '\n');
        high_boundary = input_file.tellg() - std::ios::pos_type{sizeof(char)};
        blocks[i - 1] = {low_boundary, high_boundary};
        low_boundary = input_file.tellg();
    }
    blocks[blocks_count - 1] = {low_boundary, file_size - 1};
    input_file.close();
    return blocks;
}
Referenced by run().
Member Data Documentation
_combiner
combiner_type MapReduce::_combiner private
Definition at line 47 of file MapReduce.h.
Referenced by set_combiner().
_combiner_out
const std::string MapReduce::_combiner_out {"combiner_out"} private
Definition at line 51 of file MapReduce.h.
Referenced by run_combiners(), and run_shuffler().
_mapper
mapper_type MapReduce::_mapper private
Definition at line 46 of file MapReduce.h.
Referenced by run_mappers(), and set_mapper().
_mapper_out
const std::string MapReduce::_mapper_out {"mapper_out"} private
Definition at line 50 of file MapReduce.h.
Referenced by run_combiners(), and run_mappers().
_mappers_count
std::size_t MapReduce::_mappers_count private
Definition at line 43 of file MapReduce.h.
Referenced by run(), run_combiners(), run_mappers(), and run_shuffler().
_reducer
reducer_type MapReduce::_reducer private
Definition at line 48 of file MapReduce.h.
Referenced by set_reducer().
_reducer_in
const std::string MapReduce::_reducer_in {"reducer_in"} private
Definition at line 52 of file MapReduce.h.
Referenced by run_reducers(), and run_shuffler().
_reducer_out
const std::string MapReduce::_reducer_out {"reducer_out"} private
Definition at line 53 of file MapReduce.h.
Referenced by get_output_filename(), and run_reducers().
_reducers_count
std::size_t MapReduce::_reducers_count private
Definition at line 44 of file MapReduce.h.
Referenced by run_reducers(), and run_shuffler().
_work
fs::path MapReduce::_work private
Definition at line 54 of file MapReduce.h.
Referenced by MapReduce(), run_combiners(), run_mappers(), run_reducers(), and run_shuffler().
The documentation for this class was generated from the following files:
MapReduce.h
MapReduce.cpp